services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: redis://redis:6379/0
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile(worker)
    depends_on:
      - rabbitmq
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      # Монтируем вашу ЛОКАЛЬНУЮ папку в выделенный путь внутри контейнера
      - ./prometheus_data:/etc/prometheus_custom
    command:
      # Указываем Прометею читать конфиг из этой кастомной папки
      - '--config.file=/etc/prometheus_custom/prometheus.yml'
      # Сохраняем системные библиотеки, чтобы веб-интерфейс работал штатно
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - alertmanager
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      # Монтируем вашу ЛОКАЛЬНУЮ папку для Alertmanager
      - ./alertmanager_data:/etc/alertmanager_custom
    command:
      - '--config.file=/etc/alertmanager_custom/alertmanager.yml'
    restart: unless-stopped

  alert-logger:
    image: python:3.11-slim
    container_name: alert-logger
    command: >
      python -c "
      from http.server import BaseHTTPRequestHandler, HTTPServer;
      import sys;
      class H(BaseHTTPRequestHandler):
          def do_POST(self):
              content_length = int(self.headers['Content-Length']);
              print('=== ALERT RECEIVED ===\n', self.rfile.read(content_length).decode(), flush=True);
              self.send_response(200); self.end_headers()
      HTTPServer(('0.0.0.0', 5000), H).serve_forever()
      "
    ports:
      - 5005:5000
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

volumes:
  sqlite_data:
  grafana_data:

networks:
  default:
    name: hello_fastapi
